### ISSUE TITLE
Add support for HEX alpha channel

### ISSUE THREAD

**Issue by equinusocio** [andyjansson/css-color-converter#3]
Hex colors with alpha channels like  are now valid CSS colors. This lib doesn't support 8-Digit hex colors:

For example `#00000099` and `#0009` produce the same color, black with `60%` alpha.

Here more info:
https://css-tricks.com/8-digit-hex-codes/

**Comment by andyjansson** [comment]
PR is welcome!

**Comment by equinusocio** [comment]
Yes. Can you indicate at least where is the issue within your code?

**Comment by andyjansson** [comment]
Hi again. It's been 5 years since I initially wrote this library, so I had a look. The library does support 8-character hex characters, as evidenced by the [tests](https://github.com/andyjansson/css-color-converter/blob/master/test/test.js#L39). Perhaps there's some issue on your end?

**Comment by andyjansson** [comment]
If you run the library on RunKit, you can also see that it produces the correct result: 

https://npm.runkit.com/css-color-converter
```js
var cssColorConverter = require("css-color-converter")
cssColorConverter("#0009").toRgbString()
```

Outputs: 

```
"rgba(0, 0, 0, 0.6)" 
```
