### ISSUE TITLE
RGB colors with mix of numbers and percentages

### ISSUE THREAD

**Issue by PyvesB** [andyjansson/css-color-converter#4]
Hello! 👋🏻 

Thanks for creating this NPM package, we're using it in [badges/shields](https://github.com/badges/shields) to compute our font colors and to perform CSS color normalisation.

I've hit kind of a weird edge-case. RGB colors with a mixture of numbers and percentages seem to be parsed happily by ccs-color-converter, for example `rgb(100%, 200, 222)`. The [CSS color specification](https://www.w3.org/TR/2018/REC-css-color-3-20180619/#rgb-color) states that "either three integer values or three percentage values" should be used, so I don't think mixing numbers and percentages within the same color is allowed. The regexes is the [new draft specification](https://www.w3.org/TR/css-color-4/#rgb-functions) indicate this as well.

What are your thoughts?

Thanks in advance for looking into this!

**Comment by andyjansson** [comment]
Hello!

I'll look into this issue after I'm done with work. In the meanwhile, could you please provide some information about how this issue first arose (what caused you to pass values of mixed units) and what do you believe the appropriate behaviour should be (e.g. should it raise an error)? 

Thank you.

**Comment by PyvesB** [comment]
The issue arose because we're switching from another package to ccs-color-converter, and basically we're looking at how different edge-cases are handled in both libraries.

I think it would be a matter of tweaking the regex: https://github.com/andyjansson/css-color-converter/blob/6f0e6a7ddd0d765cbc07b6c73c75cffc22dfa2b1/index.js#L10 Possibly the one for RGBA as well. But I wouldn't expect an error to be explicitly raised: the input should simply not meet any of the conditionals, as would other invalid inputs today.

**Comment by andyjansson** [comment]
Hi again. 

Just letting you know that I've conducted a rewrite of the library. As a consequence, the API surface has been altered. Aside from code changes, the library should now be more in line with the CSS Color Module Level 4 specification, including: 

- A fix for treating the arguments to `rgb` & `rgba` as either numbers or percentages, not a mix of both. 
- Aliased `rgb` & `rgba` as well as `hsl` & `hlsa`. 
- Added support for the new space-separated syntax for `rgb`, `rgba`, `hsl` & `hsla`. 

I have not yet published this new version. It would be great if you could give it a spin before I do. 

Thanks.

**Comment by PyvesB** [comment]
Thanks, will aim at giving it a go in the coming days.

**Comment by PyvesB** [comment]
I tried integrating the rewrite in a local copy of shields, but I've not managed to get things to work. The conversion to an ES6 module seems to have confused things, and unfortunately I don't know enough about this new thing to quickly figure out if it's resolvable or not within our Node.js setup.

**Comment by andyjansson** [comment]
That's interesting. Are you getting any specific error? Also, what version of node are you running?

**Comment by PyvesB** [comment]
Basically here's what I've tried:
* I manually replaced _index.js_ with _index.mjs_ (and the filename in _package.json_) in my local _node_modules/css-color-converter_ folder. I got the following error: `Must use import to load ES Module` when running some unit tests.
* inside the Shields code, I then replaced `const cssColorConverter = require('css-color-converter')` with `import cssColorConverter from 'css-color-converter'`. The error changed to `Cannot use import statement outside a module`.
* I added `"type": "module"` to Shields's _badge-maker/package.json_. The error became `require is not defined` as we've got many requires all over the code base.

I'm using Node 14.2.0 locally, our production server runs on Node 12 and our badge-maker NPM package still guarantees compatibility for Node 10.

**Comment by andyjansson** [comment]
It would appear that ES modules in Node.js isn't ready for prime time yet, unfortunately. I was hoping I could get away with not adding babel to the project, but I guess I was mistaken. I'll get around to it this weekend. 

PS. You can install the package directly from git using `npm i git+https://github.com/andyjansson/css-color-converter`, so no need to manually fiddle with the files in `node_modules`.

**Comment by PyvesB** [comment]
> 
> PS. You can install the package directly from git using `npm i git+https://github.com/andyjansson/css-color-converter`, so no need to manually fiddle with the files in `node_modules`.

Thanks for the tip, will keep it in mind for next time!

**Comment by andyjansson** [comment]
Hello, 

I've now added babel into the mix, so hopefully things should work a bit better for you. Unfortunately, you can no longer use the aforementioned install command since there is now a build step involved, so I'm afraid you're back to fiddling with `node_modules`. Sorry about that. 

To compile the files run `npm run build` and a `lib` folder will be produced with the required files. Make sure that you have the latest `package.json` as well since this points toward `lib/index.js`.

Thanks again.

**Comment by PyvesB** [comment]
I've managed to get things working successfully with your latest changes. From what I can tell from our test cases, the new version of the library seems compliant with the CSS color specification. 👍🏻 

As a suggestion, maybe make throwing the `Cannot parse string` error optional and return `undefined` instead? Or possibly add a separate `isValidString` function? We partly use the library for validation, it's always nicer to be able to put a check in an `if` condition rather than having to write a try/catch block which may end up suppressing other errors than the one we're expecting.

**Comment by andyjansson** [comment]
>As a suggestion, maybe make throwing the Cannot parse string error optional and return undefined instead? Or possibly add a separate isValidString function? We partly use the library for validation, it's always nicer to be able to put a check in an if condition rather than having to write a try/catch block which may end up suppressing other errors than the one we're expecting.

I've updated the code to return `null` instead of raising an error if the string doesn't match any of the supported formats. Hopefully that's better for you.

**Comment by PyvesB** [comment]
Thanks, that's better.

I also checked that there were no big performance regressions by running a micro-benchmark on the css-color-converter library calls within a running Shields.io instance. Performance seems to be pretty much on par, even slightly better actually.

I have no outstanding concerns nor suggestions, all is good from my perspective. :)

**Comment by andyjansson** [comment]
Hi. Just letting you know that the new version has been published to npm. Thanks for your help! 😄

**Comment by PyvesB** [comment]
Great stuff, thanks for the update!
